### ISSUE TITLE
TTL in configuration

### ISSUE THREAD

**Issue by infodavidgit** [internetitem/logback-elasticsearch-appender#11]
Hi Adam,

Is it possible to add the TTL in configuration even if it will change in next releases of ES ?

Best regards,
david

**Comment by abatkin** [comment]
Would it work to just have another property called "`_ttl`" and use that?

    <property>
        <name>_ttl</name>
        <value>10m</value>
    </property>

**Comment by infodavidgit** [comment]
Hi Adam,

It does not work with the current release. Seems that adding the property implies a failure when posting the data to ES.

Regarding the pull request made by Maksim, do you think it will be merged in the coming days ?

Best regards,
david

**Comment by abatkin** [comment]
I'm fine with figuring out how to include _ttl but it's unclear to me from the [documentation for the bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-ttl) how/where the _ttl field should be included.

The other PR for HTTP Basic auth is fine in principle, it just needs to be cleaned up a bit, and maybe the certificate validation stuff moved to a different PR so it can be discussed independently.

**Comment by infodavidgit** [comment]
Normally, the _ttl must be posted in the same way as _index. So, it must be specified beside the index element and not in the properties of the appender.

Regarding the authentication, I agree to merge it independently but as I wrote, it will be nice to have it working with both HTTPS and HTTP.

The feature associated must include an enhancement to verify the certificate but a boolean parameter in the appender configuration could be added to specify if all must be trusted or if a check must be done.

**Comment by infodavidgit** [comment]
Adam, if you need some help, do not hesitate to ask me

**Comment by infodavidgit** [comment]
@abatkin do I have to make the feature available by submitting a new pull request or do you intend to implement this enhancement ?

**Comment by abatkin** [comment]
@infodavidgit if you wanted to take a stab, that wouldn't be a bad idea, since then you could also test it in your environment to make sure that it works correctly
