### ISSUE TITLE
Release 1.3 please ;-)

### ISSUE THREAD

**Issue by dmcg** [internetitem/logback-elasticsearch-appender#14]
I'd really like to use `rawJsonMessage` so that I can write queries against my log messages.

**Comment by abatkin** [comment]
Agreed. Will try to do a release today or tomorrow

**Comment by dmcg** [comment]
Thanks - you've already dug me out of a logging hole by sharing the code. Much appreciated.

**Comment by abatkin** [comment]
1.3 has been released. Let me know if you have any issues.

**Comment by dmcg** [comment]
Thanks
