### ISSUE TITLE
Message string format

### ISSUE THREAD

**Issue by pinhasyak** [internetitem/logback-elasticsearch-appender#3]
Hi,

Thank you for useful framework,
When I use logger pattern like this:
LOGGER.error("Producing failed, going to try again in {} seconds", this.sleepDelaySeconds, e);
I get {message:Producing failed, going to try again in {} seconds}
I expect to get : {message:Producing failed, going to try again in 5 seconds}

Sincerely,
Pinhas

**Comment by pinhasyak** [comment]
Hi,

In ClassicElasticsearchPublisher 
line 37, please use :  gen.writeObjectField("message", event.getFormattedMessage());

**Comment by abatkin** [comment]
Thank you for catching that (and the fix). I've released v1.1 to Maven Central which includes the change (as well as some small documentation improvements and Logback Access support).
