### ISSUE TITLE
allow granularity of @timestamp to be configured

### ISSUE THREAD

**Issue by w39hh** [internetitem/logback-elasticsearch-appender#35]
We make heavy use of this appender in a production environment with multiple instances of micro-services running across a cluster.  Having all the micro-service instances log in near real-time directly into Elasticsearch has become core functionality.  However, unless we have missed something, the granularity of @timestamp is second.  As we have many threads running in many micro-services that level of granularity is not enough for us to get a sequenced set of events when we are exploring an issue.  We need at least millisecond granularity to sequence the log events correctly.  Is there some way we can change the granularity of @timestamp to millisecond?  Thanks enormously for a great tool!

**Comment by abatkin** [comment]
Indeed - it appears that the date format is incorrect. Let me see what I can do...

**Comment by abatkin** [comment]
Okay that was easier than I thought. Fixed in 53295a3

(will try to do a proper release soon too)
