### ISSUE TITLE
Content-Type header [text/plain] is not supported

### ISSUE THREAD

**Issue by caryyu** [internetitem/logback-elasticsearch-appender#50]
# Elasticsearch Version
6.2.4

# Output below by errorsToStderr = true
> Failed to send events to Elasticsearch: Got response code [406] from server with data {"error":"Content-Type header [text/plain] is not supported","status":406}

**Comment by abatkin** [comment]
Perhaps you could try changing the content type to something else, maybe `application/json`?

```xml
        <headers>
            <header>
                <name>Content-Type</name>
                <value>application/json</value>
            </header>
        </headers>

**Comment by caryyu** [comment]
@abatkin thx, that works.
