### ISSUE TITLE
Content-Type text/plain?

### ISSUE THREAD

**Issue by clgoh** [internetitem/logback-elasticsearch-appender#55]
Hi,

Excuse me if I'm misusing this but I couldn't find any more direct channel of communication. This is more of a question rather than issue: 
[Under the usage section of the README.md](https://github.com/internetitem/logback-elasticsearch-appender/blob/master/README.md#usage) there is a `<header>` element under the appender configuration block.

When should we decide to use `text/plain` when when should we use something else? Why was it `text/plain` instead of `application/x-ndjson` like what is described on [ElasticSearch's API Official Doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)

Thank you in advance!

Best Regards,
Lim

**Comment by ewolff** [comment]
I suspect this is an error. More recent versions of Elasticsearch require a content type of `application/json` if JSON is transferred. If you use the configuration as provided, this leads to an error.
I have created a PR: https://github.com/internetitem/logback-elasticsearch-appender/pull/58

**Comment by abatkin** [comment]
That makes sense, I've merged the PR which updates the README
