### ISSUE TITLE
Is there a config that allow me to rolling the logs by date or size?

### ISSUE THREAD

**Issue by loriling** [internetitem/logback-elasticsearch-appender#60]
Like RollingFileAppender, the logs data will become bigger and bigger if we do not delete the old indexes, but i can not file a config in the doc that allow me to do the delete operation.

**Comment by abatkin** [comment]
Sounds like an ElasticSearch issue, not something specific to this logback appender. A common pattern is to use (for example) an index-per-day, a virtual index to make them look like one big index, and then something like [Curator](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html) to manage rolling off indices or whatever else you want to do.
